marketSensitive = [
        'Balance of payments for the UK:',
        'Business investment in the UK',
        'Construction output in Great Britain:',
        'Economic well-being:',
        'Gross domestic product, preliminary estimate:',
        'Public sector employment, UK:',
        'Regional labour market statistics in the UK:',
        'Retail Sales in Great Britain:',
        'UK consumer price inflation:',
        'UK economic accounts:',
        'UK GDP, preliminary estimate:',
        'UK GDP, second estimate:',
        'UK index of production:',
        'UK index of services:',
        'UK labour market statistics:',
        'UK producer price inflation:',
        'UK public sector finances:',
        'UK quarterly national accounts:',
        'UK trade in goods by classification of product by activity (CPA 2008):',
        'UK trade:'
    ];

timeseriesData = [
        'Balance of payments for the UK:',
        'Business enterprise research and development in the UK:',
        'Business investment in the UK',
        'Capital stock and consumption of fixed capital in the UK:',
        'Gross domestic product, preliminary estimate:',
        'Investment by insurance companies, pension funds and trusts in the UK',
        'Mergers and acquisitions involving UK companies:',
        'Overseas travel and tourism, monthly provisional results:',
        'Profitability of UK Companies:',
        'Public sector employment, UK:',
        'Retail Sales in Great Britain:',
        'The Blue Book',
        'Turnover and orders in UK production and Great Britain services industries',
        'UK consumer price inflation:',
        'UK consumer trends:',
        'UK economic accounts:',
        'UK GDP, preliminary estimate:',
        'UK GDP, second estimate:',
        'UK index of production:',
        'UK index of services:',
        'UK labour market statistics:',
        'UK national accounts:',
        'UK producer price inflation:',
        'UK productivity:',
        'UK public sector finances:',
        'UK quarterly national accounts:',
        'UK services producer price index',
        'UK trade in goods by classification of product by activity',
        'UK trade:',
        'United Kingdom Balance of Payments, The Pink Book:'
    ];

dashboardData = [
        'UK GDP, preliminary estimate:',
        'UK GDP, second estimate:',
        'UK quarterly national accounts:',
        'UK consumer price inflation:',
        'UK index of production:',
        'UK index of services:',
        'Construction output in Great Britain:',
        'Retail Sales in Great Britain:',
        'Business investment in the UK',
        'UK labour market statistics:',
	'UK house price index:',
        'UK producer price inflation:',
        'UK trade:'
    ];

trackingTable = [
	"Balance of payments for the UK:", 
	"Business investment in the UK", 
	"Construction output in Great Britain:", 
	"UK consumer price inflation:", 
	"UK consumer trends:", 
	"Economic well-being:", 
	"UK GDP, preliminary estimate:", 
	"UK quarterly national accounts:", 
	"UK house price index:", 
	"UK index of production:", 
	"UK index of services:", 
	"Investment by insurance companies, pension funds and trusts in the UK (MQ5):", 
	"UK labour market statistics:", 
	//"Migration in the UK:", Removed temporarily
	"Overseas travel and tourism, monthly provisional results:", 
	"UK population by country of birth and nationality:", 
	"Population estimates for UK, England and Wales, Scotland and Northern Ireland:", 
	"UK producer price inflation:", "UK public sector finances:", 
	"Retail sales in Great Britain:", 
	"UK productivity:", 
	"UK trade:"
    ];
